package net.bramp.dissector.disk;

import com.google.common.collect.ImmutableMap;
import net.bramp.dissector.io.ExtendedRandomAccessFile;
import net.bramp.dissector.node.*;

import java.io.IOException;
import java.util.Map;

/**
 * @author bramp
 */
public class PartitionEntryNode extends TreeNode {

    /*
    // List thankfully taken from http://www.datarecovery.com/hexcodes.asp
    static final Map<Integer, String> partitionTypes = ImmutableMap.<Integer, String>builder()
        .put(0x00, "No Partition")
        .put(0x01, "DOS 12-bit FAT")
        .put(0x02, "XENIX root file system")
        .put(0x03, "XENIX /usr file system (obsolete)")
        .put(0x04, "DOS 16-bit FAT (up to 32M)")
        .put(0x05, "Extended DOS 3.3+ extended partition")
        .put(0x06, "DOS 3.31+ Large File System (16-bit FAT, over 32M)")
        .put(0x07, "Advanced Unix / QNX / OS2 HPFS / WindowsNT NTFS")
        .put(0x08, "OS/2 (v1.0-1.3 only)")
        .put(0x08, "AIX bootable partition, SplitDrive")
        .put(0x08, "Commodore Commodore DOS")
        .put(0x08, "DELL partition spanning multiple drives")
        .put(0x09, "Coherent Coherent filesystem")
        .put(0x09, "AIX data partition")
        .put(0x0A, "OPUS")
        .put(0x0A, "Coherent Coherent swap partition")
        .put(0x0A, "OS/2 OS/2 Boot Manager")
        .put(0x0B, "Windows95 with 32-bit FAT")
        .put(0x0C, "Windows95 with 32-bit FAT (using LBA-mode INT 13 extensions)")
        .put(0x0E, "VFAT logical-block-addressable VFAT")
        .put(0x0F, "Extended LBA Extended partition")
        .put(0x10, "OPUS")
        .put(0x11, "FAT12 OS/2 Boot Manager hidden 12-bit FAT partition")
        .put(0x12, "Compaq Compaq Diagnostics partition")
        .put(0x14, "FAT16 OS/2 Boot Manager hidden sub-32M 16-bit FAT partition")
        .put(0x16, "FAT16 OS/2 Boot Manager hidden over-32M 16-bit FAT partition")
        .put(0x17, "OS/2 OS/2 Boot Manager hidden HPFS partition")
        .put(0x17, "NTFS hidden")
        .put(0x18, "ASTSuspend AST special Windows swap file (\"Zero-Volt Suspend\" partition)")
        .put(0x19, "Willowtech Photon coS")
        .put(0x1B, "Windows hidden Windows95 FAT32 partition")
        .put(0x1C, "Windows hidden Windows95 FAT32 partition (LBA-mode)")
        .put(0x1E, "Windows hidden LBA VFAT partition")
        .put(0x20, "Willowsoft Overture File System (OFS1)")
        .put(0x21, "[reserved]")
        .put(0x21, "FSo2")
        .put(0x23, "[reserved]")
        .put(0x24, "NEC MS-DOS 3.x")
        .put(0x26, "[reserved]")
        .put(0x31, "[reserved]")
        .put(0x33, "[reserved]")
        .put(0x34, "[reserved]")
        .put(0x36, "[reserved]")
        .put(0x38, "Theos")
        .put(0x3C, "PowerQuest PartitionMagic recovery partition")
        .put(0x40, "VENIX 80286")
        .put(0x41, "Personal RISC Boot")
        .put(0x41, "PowerPC boot partition")
        .put(0x42, "SFS(Secure File System) by Peter Gutmann")
        .put(0x45, "EUMEL/Elan")
        .put(0x46, "EUMEL/Elan")
        .put(0x47, "EUMEL/Elan")
        .put(0x48, "EUMEL/Elan")
        .put(0x4F, "Oberon Oberon boot/data partition")
        .put(0x50, "OnTrack Disk Manager, read-only partition")
        .put(0x51, "OnTrack Disk Manager, read/write partition")
        .put(0x51, "NOVELL")
        .put(0x52, "CP/M")
        .put(0x52, "Microport System V/386")
        .put(0x53, "OnTrack Disk Manager, write-only partition???")
        .put(0x54, "OnTrack Disk Manager (DDO)")
        .put(0x55, "EZ-Drive")
        .put(0x56, "GoldenBow VFeature")
        .put(0x5C, "Priam EDISK")
        .put(0x61, "SpeedStor ")
        .put(0x63, "UnixSysV Unix SysV/386, 386/ix")
        .put(0x63, "Mach Mach, MtXinu BSD 4.3 on Mach")
        .put(0x63, "GNU-HURD GNU HURD")
        .put(0x64, "Novell Novell NetWare 286")
        .put(0x64, "SpeedStore SpeedStore")
        .put(0x65, "Novell NetWare (3.11)")
        .put(0x67, "Novell")
        .put(0x68, "Novell")
        .put(0x69, "Novell NSS Volume")
        .put(0x70, "DiskSecure DiskSecure Multi-Boot")
        .put(0x71, "[reserved]")
        .put(0x73, "[reserved]")
        .put(0x74, "[reserved]")
        .put(0x75, "PC/IX")
        .put(0x76, "[reserved]")
        .put(0x7E, "F.I.X.")
        .put(0x80, "Minix v1.1 - 1.4a")
        .put(0x81, "Minix v1.4b+")
        .put(0x81, "Linux")
        .put(0x81, "Mitac Advanced Disk Manager")
        .put(0x82, "Linux/Swap Linux Swap partition")
        .put(0x82, "Prime")
        .put(0x82, "Solaris (Unix)")
        .put(0x83, "Linux native file system (ext2fs/xiafs)")
        .put(0x84, "DOS OS/2-renumbered type 04h partition (hiding DOS C: drive)")
        .put(0x85, "Linux EXT")
        .put(0x86, "FAT16 volume/stripe set (Windows NT)")
        .put(0x87, "HPFS Fault-Tolerant mirrored partition")
        .put(0x87, "NTFS volume/stripe set")
        .put(0x93, "Amoeba file system")
        .put(0x94, "Amoeba bad block table")
        .put(0x98, "Datalight Datalight ROM-DOS SuperBoot")
        .put(0x99, "Mylex EISA SCSI")
        .put(0xA0, "Phoenix NoteBIOS Power Management \"Save-to-Disk\" partition")
        .put(0xA1, "[reserved]")
        .put(0xA3, "[reserved]")
        .put(0xA4, "[reserved]")
        .put(0xA5, "FreeBSD, BSD/386")
        .put(0xA6, "OpenBSD")
        .put(0xA9, "NetBSD")
        .put(0xB1, "[reserved]")
        .put(0xB3, "[reserved]")
        .put(0xB4, "[reserved]")
        .put(0xB6, "[reserved]")
        .put(0xB6, "Windows NT mirror set (master), FAT16 file system")
        .put(0xB7, "BSDI file system (secondarily swap)")
        .put(0xB7, "Windows NT mirror set (master), NTFS file system")
        .put(0xB8, "BSDI swap partition (secondarily file system)")
        .put(0xBE, "Solaris boot partition")
        .put(0xC0, "CTOS")
        .put(0xC0, "DR-DOS DR DOS/DR-DOS/Novell DOS secured partition")
        .put(0xC1, "DR-DOS 6.0 LOGIN.EXE-secured 12-bit FAT partition")
        .put(0xC4, "DR-DOS 6.0 LOGIN.EXE-secured 16-bit FAT partition")
        .put(0xC6, "DR-DOS 6.0 LOGIN.EXE-secured Huge partition")
        .put(0xC6, "corrupted corrupted FAT16 volume/stripe set (Windows NT)")
        .put(0xC6, "Windows NT mirror set (slave), FAT16 file system")
        .put(0xC7, "Syrinx Boot")
        .put(0xC7, "corrupted NTFS volume/stripe set")
        .put(0xC7, "Windows NT mirror set (slave), NTFS file system")
        .put(0xCB, "DR-DOS/OpenDOS secured FAT32")
        .put(0xCC, "DR-DOS secured FAT32 (LBA)")
        .put(0xCE, "DR-DOS secured FAT16 (LBA)")
        .put(0xD0, "Multiuser DOS secured FAT12")
        .put(0xD1, "Old-FAT12 Old Multiuser DOS secured FAT12")
        .put(0xD4, "Old-FAT16 Old Multiuser DOS secured FAT16 (<= 32M)")
        .put(0xD5, "Old-Ext Old Multiuser DOS secured extended partition")
        .put(0xD6, "Old-FAT16 Old Multiuser DOS secured FAT16 (> 32M)")
        .put(0xD8, "CP/M-86 CP/M-86")
        .put(0xDB, "CP/M CP/M, Concurrent CP/M, Concurrent DOS")
        .put(0xDB, "CTOS CTOS (Convergent Technologies OS)")
        .put(0xE1, "SpeedStor SpeedStor 12-bit FAT extended partition")
        .put(0xE2, "DOS read-only (Florian Painke's XFDISK 1.0.4)")
        .put(0xE3, "DOS read-only")
        .put(0xE3, "Storage Dimensions")
        .put(0xE4, "SpeedStor 16-bit FAT extended partition")
        .put(0xE5, "[reserved]")
        .put(0xE6, "[reserved]")
        .put(0xEB, "BeOS BFS (BFS1)")
        .put(0xF1, "Storage Dimensions")
        .put(0xF2, "DOS 3.3+ secondary partition")
        .put(0xF3, "[reserved]")
        .put(0xF4, "SpeedStor")
        .put(0xF4, "Storage Dimensions")
        .put(0xF5, "Prologue")
        .put(0xF6, "[reserved]")
        .put(0xFB, "VMWARE partition")
        .put(0xFE, "LANstep")
        .put(0xFE, "PS/2-IML IBM PS/2 IML (Initial Microcode Load) partition")
        .put(0xFF, "Xenix bad block table")
        .build();
    */

    // Taken from fdisk/src/sys_types.h
    static final Map<Integer, String> partitionTypes = ImmutableMap.<Integer, String>builder()
        .put(0x00, "Empty")
        .put(0x01, "FAT12")
        .put(0x02, "XENIX root")
        .put(0x03, "XENIX usr")
        .put(0x04, "Small FAT16")
        .put(0x05, "Extended")
        .put(0x06, "FAT16")
        .put(0x07, "HPFS/NTFS")
        .put(0x08, "AIX")
        .put(0x09, "AIX bootable")
        .put(0x0a, "OS/2 boot mgr")
        .put(0x0b, "FAT32")
        .put(0x0c, "FAT32 LBA")
        .put(0x0e, "FAT16 LBA")
        .put(0x0f, "Extended LBA")
        .put(0x10, "OPUS")
        .put(0x11, "Hidden FAT12")
        .put(0x12, "Compaq diag")
        .put(0x14, "Hidd Sm FAT16")
        .put(0x16, "Hidd FAT16")
        .put(0x17, "Hidd HPFS/NTFS")
        .put(0x18, "AST SmartSleep")
        .put(0x1b, "Hidd FAT32")
        .put(0x1c, "Hidd FAT32 LBA")
        .put(0x1e, "Hidd FAT16 LBA")
        .put(0x24, "NEC DOS")
        .put(0x27, "Hidden NTFS WinRE")
        .put(0x39, "Plan 9")
        .put(0x3c, "PMagic recovery")
        .put(0x40, "Venix 80286")
        .put(0x41, "PPC PReP Boot")
        .put(0x42, "SFS")
        .put(0x4d, "QNX4.x")
        .put(0x4e, "QNX4.x 2nd part")
        .put(0x4f, "QNX4.x 3rd part")
        .put(0x50, "OnTrack DM")
        .put(0x51, "OnTrackDM6 Aux1")
        .put(0x52, "CP/M")
        .put(0x53, "OnTrackDM6 Aux3")
        .put(0x54, "OnTrack DM6")
        .put(0x55, "EZ Drive")
        .put(0x56, "Golden Bow")
        .put(0x5c, "Priam Edisk")
        .put(0x61, "SpeedStor")
        .put(0x63, "GNU HURD/SysV")
        .put(0x64, "Netware 286")
        .put(0x65, "Netware 386")
        .put(0x70, "DiskSec MltBoot")
        .put(0x75, "PC/IX")
        .put(0x80, "Minix <1.4a")
        .put(0x81, "Minix >1.4b")
        .put(0x82, "Linux swap")
        .put(0x83, "Linux")
        .put(0x84, "OS/2 hidden C:")
        .put(0x85, "Linux extended")
        .put(0x86, "NTFS volume set")
        .put(0x87, "NTFS volume set")
        .put(0x88, "Linux plaintext")
        .put(0x8e, "Linux LVM")
        .put(0x93, "Amoeba")
        .put(0x94, "Amoeba BBT")
        .put(0x9f, "BSD/OS")
        .put(0xa0, "Thinkpad hib")
        .put(0xa5, "FreeBSD")
        .put(0xa6, "OpenBSD")
        .put(0xa7, "NeXTSTEP")
        .put(0xa8, "Darwin UFS")
        .put(0xa9, "NetBSD")
        .put(0xab, "Darwin boot")
        .put(0xaf, "HFS / HFS+")
        .put(0xb7, "BSDI fs")
        .put(0xb8, "BSDI swap")
        .put(0xbb, "Boot Wizard Hidden")
        .put(0xbe, "Solaris boot")
        .put(0xbf, "Solaris")
        .put(0xc1, "DRDOS/2 FAT12")
        .put(0xc4, "DRDOS/2 smFAT16")
        .put(0xc6, "DRDOS/2 FAT16")
        .put(0xc7, "Syrinx")
        .put(0xda, "Non-FS data")
        .put(0xdb, "CP/M / CTOS")
        .put(0xde, "Dell Utility")
        .put(0xdf, "BootIt")
        .put(0xe1, "DOS access")
        .put(0xe3, "DOS R/O")
        .put(0xe4, "SpeedStor")
        .put(0xfb, "VMware VMFS")
        .put(0xfc, "VMware VMKCORE")
        .put(0xeb, "BeOS fs")
        .put(0xee, "GPT")
        .put(0xef, "EFI FAT")
        .put(0xf0, "Lnx/PA-RISC bt")
        .put(0xf1, "SpeedStor")
        .put(0xf2, "DOS secondary")
        .put(0xf4, "SpeedStor")
        .put(0xfd, "Lnx RAID auto")
        .put(0xfe, "LANstep")
        .put(0xff, "XENIX BBT")
        .build();

    public PartitionEntryNode read(ExtendedRandomAccessFile in) throws IOException {
        //addChild("skip", new FixedStringNode().read(in, 16) );
        addChild("status", new ByteNode().read(in).base(16) );
        addChild("first sector (chs)", new CHSAddressNode().read(in));
        addChild("type", new EnumNode(partitionTypes).read(in, 1));
        addChild("last sector (chs)", new CHSAddressNode().read(in));

        addChild("LBA first sector", new IntNode().read(in).base(16) );
        addChild("number of sectors", new IntNode().read(in) );
        return this;
    }

}
